"""Renter-facing packet PDF, styled to match the app's ledger/case-file design:
paper background, white cards, ink text, sage/rust status colors, highlighter accents,
and the RealDoor doorframe mark in the header."""

import io
from datetime import date

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

# Palette mirrors frontend/src/app/globals.css.
INK = HexColor("#15201B")
PAPER = HexColor("#F2F1E9")
CARD = HexColor("#FFFFFF")
SAGE = HexColor("#5E7A5C")
RUST = HexColor("#A2503B")
HIGHLIGHTER = HexColor("#E8B23D")
BORDER = HexColor("#DDDAD0")
MUTED = HexColor("#6B6B5F")

PAGE_W, PAGE_H = letter
MARGIN = 54
CARD_PAD = 16
ROW_H = 20

# Renter-friendly labels, mirroring the profile page's FIELD_LABELS.
FIELD_LABELS = {
    "gross_pay": "Gross pay (per period)",
    "hourly_rate": "Hourly rate",
    "net_pay": "Net pay",
    "pay_date": "Pay date",
    "pay_frequency": "Pay frequency",
    "pay_period_start": "Pay period start",
    "pay_period_end": "Pay period end",
    "person_name": "Name",
    "regular_hours": "Regular hours",
    "household_size": "Household size",
    "address": "Address",
    "application_date": "Application date",
    "document_date": "Document date",
    "weekly_hours": "Weekly hours",
    "benefit_frequency": "Benefit frequency",
    "monthly_benefit": "Monthly benefit",
    "gross_receipts": "Gross receipts",
    "platform_fees": "Platform fees",
    "statement_month": "Statement month",
}

STATUS_META = {
    "present": (SAGE, "Present"),
    "missing": (RUST, "Missing"),
    "expired": (RUST, "Expired"),
}


def _label(field_name: str) -> str:
    return FIELD_LABELS.get(field_name, field_name.replace("_", " ").capitalize())


def _money(value) -> str:
    try:
        return f"${float(value):,.2f}"
    except (TypeError, ValueError):
        return str(value)


def _draw_logo(c: canvas.Canvas, x: float, y: float, size: float = 22) -> None:
    """The doorframe mark from the app header: outer rounded square, inner door jamb."""
    s = size / 26.0
    c.setStrokeColor(INK)
    c.setLineWidth(2)
    c.roundRect(x, y, size, size, 3 * s, stroke=1, fill=0)
    c.setLineWidth(1.6)
    c.line(x + 16 * s, y + 8 * s, x + 16 * s, y + 20 * s)


def _paint_page(c: canvas.Canvas, page_num: int) -> float:
    """Paper background + footer; returns the starting y cursor for content."""
    c.setFillColor(PAPER)
    c.rect(0, 0, PAGE_W, PAGE_H, stroke=0, fill=1)

    c.setFont("Helvetica", 7.5)
    c.setFillColor(MUTED)
    c.drawString(
        MARGIN,
        30,
        "Generated by RealDoor — assistive, not adjudicative. This packet is not an eligibility determination.",
    )
    c.drawRightString(PAGE_W - MARGIN, 30, f"Page {page_num}")
    return PAGE_H - MARGIN


def _draw_header(c: canvas.Canvas, y: float) -> float:
    _draw_logo(c, MARGIN, y - 22)
    c.setFillColor(INK)
    c.setFont("Courier-Bold", 16)
    c.drawString(MARGIN + 32, y - 16, "RealDoor")
    c.setFont("Helvetica", 9)
    c.setFillColor(MUTED)
    c.drawRightString(PAGE_W - MARGIN, y - 16, f"Prepared {date.today().isoformat()}")

    y -= 40
    c.setFillColor(INK)
    c.setFont("Helvetica-Bold", 19)
    c.drawString(MARGIN, y, "Application-Readiness Packet")
    y -= 16
    c.setFont("Helvetica", 9.5)
    c.setFillColor(MUTED)
    c.drawString(MARGIN, y, "A summary of your confirmed profile, income comparison, and document checklist.")

    # Highlighter underline accent beneath the title block.
    y -= 12
    c.setFillColor(HIGHLIGHTER)
    c.rect(MARGIN, y, 72, 3, stroke=0, fill=1)
    return y - 22


def _draw_card(c: canvas.Canvas, y: float, title: str, rows: list, row_height: float = ROW_H) -> float:
    """A white rounded card with a caps section title and label/value (or custom) rows.
    Each row is (draw_fn) taking (canvas, x, baseline_y, inner_width)."""
    height = CARD_PAD * 2 + 16 + len(rows) * row_height
    top = y
    bottom = top - height
    c.setFillColor(CARD)
    c.setStrokeColor(BORDER)
    c.setLineWidth(1)
    c.roundRect(MARGIN, bottom, PAGE_W - 2 * MARGIN, height, 6, stroke=1, fill=1)

    inner_x = MARGIN + CARD_PAD
    inner_w = PAGE_W - 2 * MARGIN - 2 * CARD_PAD
    cursor = top - CARD_PAD - 10
    c.setFillColor(MUTED)
    c.setFont("Courier-Bold", 9)
    c.drawString(inner_x, cursor, title.upper())
    cursor -= 6

    for draw_row in rows:
        cursor -= row_height
        c.setStrokeColor(HexColor("#EEECE4"))
        c.setLineWidth(0.75)
        c.line(inner_x, cursor + row_height - 6, inner_x + inner_w, cursor + row_height - 6)
        draw_row(c, inner_x, cursor, inner_w)

    return bottom - 18


def _kv_row(label: str, value: str, value_color=INK, mono: bool = True):
    def draw(c, x, y, w):
        c.setFillColor(MUTED)
        c.setFont("Helvetica", 9.5)
        c.drawString(x, y, label)
        c.setFillColor(value_color)
        c.setFont("Courier-Bold" if mono else "Helvetica-Bold", 10)
        c.drawRightString(x + w, y, value)

    return draw


def _checklist_row(item: dict):
    color, status_label = STATUS_META.get(item["status"], (MUTED, item["status"]))

    def draw(c, x, y, w):
        # Status dot + text label (never color alone).
        c.setFillColor(color)
        c.circle(x + 4, y + 3, 3.5, stroke=0, fill=1)
        c.setFillColor(INK)
        c.setFont("Helvetica", 9.5)
        c.drawString(x + 14, y, item["label"])
        c.setFillColor(color)
        c.setFont("Helvetica-Bold", 9)
        c.drawRightString(x + w, y, status_label.upper())

    return draw


def render_packet_pdf(profile: dict, calculation: dict, checklist: list[dict]) -> bytes:
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    c.setTitle("RealDoor Application-Readiness Packet")

    page_num = 1
    y = _paint_page(c, page_num)
    y = _draw_header(c, y)

    def ensure_room(y: float, needed: float) -> float:
        nonlocal page_num
        if y - needed < MARGIN:
            c.showPage()
            page_num += 1
            return _paint_page(c, page_num)
        return y

    # --- Confirmed profile ---
    profile_rows = [_kv_row(_label(name), str(value)) for name, value in profile.items()]
    y = ensure_room(y, CARD_PAD * 2 + 16 + len(profile_rows) * ROW_H + 18)
    y = _draw_card(c, y, "Confirmed profile", profile_rows)

    # --- Income vs threshold ---
    gap = calculation.get("gap", 0)
    gap_color = RUST if gap > 0 else SAGE
    gap_text = f"{'+' if gap >= 0 else '-'}{_money(abs(gap))} /yr"
    income_rows = [
        _kv_row("Confirmed annual income", f"{_money(calculation.get('confirmed_value'))} /yr"),
        _kv_row("HUD income limit", f"{_money(calculation.get('threshold'))} /yr"),
        _kv_row("Difference (income − limit)", gap_text, value_color=gap_color),
        _kv_row("Formula", str(calculation.get("formula", "")), mono=False),
        _kv_row("Source", str(calculation.get("source_citation", "")), mono=False),
        _kv_row("Effective date", str(calculation.get("effective_date", ""))),
    ]
    y = ensure_room(y, CARD_PAD * 2 + 16 + len(income_rows) * ROW_H + 40)
    y = _draw_card(c, y, "Income vs. threshold", income_rows)

    c.setFillColor(MUTED)
    c.setFont("Helvetica-Oblique", 8.5)
    c.drawString(
        MARGIN + 2,
        y + 6,
        "These are the numbers, not a verdict — eligibility is decided by your property or housing authority.",
    )
    y -= 10

    # --- Checklist ---
    checklist_rows = [_checklist_row(item) for item in checklist]
    y = ensure_room(y, CARD_PAD * 2 + 16 + len(checklist_rows) * ROW_H + 18)
    y = _draw_card(c, y, "Document checklist", checklist_rows)

    c.showPage()
    c.save()
    return buffer.getvalue()
